version: '3'

services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - jupyter-data:/home/jovyan
    environment:
      - JUPYTER_ENABLE_LAB=yes

volumes:
  jupyter-data:
